### ISSUE TITLE
Error: ID not found

### ISSUE THREAD

**Issue by ghost** [pgdouyon/vim-evanesco#11]
I'm not sure how exactly to reproduce the bug, but it happens when I search for something, hit `n` several times, and then immediately after that hit `<C-6>` to switch buffers.

Maybe the fact that I hit all these keys in quick succession has something to do with the problem, but I'm not sure.

`:messages` display the following errors:

```
Error detected while processing function <SNR>128_toggle_hlsearch[11]..<SNR>128_set_nohlsearch[2]..<SNR>128_clear_current_match:
line    8:
E803: ID not found: 6032
"src/quicksort.rs" 743 lines --76%-- ((1) of 31)
Error detected while processing function <SNR>128_toggle_hlsearch[11]..<SNR>128_set_nohlsearch[2]..<SNR>128_clear_current_match:
line    8:
E803: ID not found: 6038
```

Here's another one:

```
Error detected while processing function <SNR>91_toggle_hlsearch[11]..<SNR>91_set_nohlsearch[2]..<SNR>91_clear_current_match:
line    8:
E803: ID not found: 22
```

**Comment by pgdouyon** [comment]
Strange, I have no idea what could possibly cause that error to be thrown seems like it shouldn't be possible since the var is unlet as soon as the match is deleted.  My guess is it's some strange race condition in Vim, but I've never seen this error before in Neovim and can't seem to reproduce it in Vim.

Nothing to do but suppress the error for now.  Try pulling down the latest and let me know if you see any other strange behavior; not sure what consequences suppressing the error could have.
