### ISSUE TITLE
s:toggle_hlsearch() is not executed when making a substitution as a first command

### ISSUE THREAD

**Issue by carmilso** [pgdouyon/vim-evanesco#12]
If you enter in vim and realize a substitution as a first command it has an unexpected behaviour due to calling the code: 
```
    if s:paused
        return
    endif
```
In function s:toggle_hlsearch()

Otherwise, if you execute a search action before the substitution it works as expected.

**Comment by pgdouyon** [comment]
I'm confused, that code should only be triggered when opening the command line window and shouldn't affect normal command execution.

When I open Vim and execute a substitution as the first command I'm not seeing anything unexpected.  Can you give more detail about what behavior you're seeing and what the expected behavior is?

**Comment by carmilso** [comment]
For example, if I am working on some file and I realize a substitution I hope not to see any word (that which I changed) highlighted. Even so, if the substitution is the first command I execute, then I see the words highlighted after executing the substitution

**Comment by pgdouyon** [comment]
Hmm I'm unable to reproduce it, when I execute a substitute as the first command I don't see any highlighting before or after executing it.  Just to clarify this highlighting occurs immediately after moving the cursor correct?  It doesn't happen after pressing the `n`/`N` keys?

Can you try with a minimal vimrc that only loads evanesco and doesn't set any other options?  Might be a particular setting that I haven't tested with.

**Comment by carmilso** [comment]
It seems a problem related to the `incsearch` option because if you remove It from this minimal vimrc the substitution works as expected.

```
set hlsearch
set incsearch

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

let g:vundle_default_git_proto = 'git'

Plugin 'VundleVim/Vundle.vim'

Plugin 'pgdouyon/vim-evanesco'

call vundle#end()

filetype plugin indent on
```

I see the words highlighted instead of moving the cursor (in fact, instead of executing any search action).

**Comment by pgdouyon** [comment]
Ahh I see, it's because `set hlsearch` is enabled.  It doesn't make sense to have that option set while using evanesco because evanesco will toggle it on/off.

I decided to just disable that setting in evanesco on startup.  It's a weird fix, but I think it's even more confusing if someone has `hlsearch` set while using evanesco.  It's also confusing because `hlsearch` defaults to off in Vim and on in Neovim.

Should be fixed if you pull the latest changes.
