### ISSUE TITLE
vim-indexed-search compatibility

### ISSUE THREAD

**Issue by dbmrq** [pgdouyon/vim-evanesco#6]
There's this little plugin, [vim-indexed-search](https://github.com/henrik/vim-indexed-search), that shows how many matches you have and what match you're at. It also remaps `/` I think, and it won't work with your plugin. It would be nice if there were a way to work around that.

Thanks for your work on this. :)

**Comment by pgdouyon** [comment]
This would be pretty difficult to fix in the general case since the Evanesco mappings are complex, but since vim-indexed-search's mappings are relatively simple you should be able to work around it with the following settings:

``` vim
let g:indexed_search_mappings = 0
nmap <silent> / :ShowSearchIndex<CR><Plug>Evanesco_/
nmap <silent> ? :ShowSearchIndex<CR><Plug>Evanesco_?
nmap <silent> n <Plug>Evanesco_n:ShowSearchIndex<CR>
nmap <silent> N <Plug>Evanesco_N:ShowSearchIndex<CR>
nmap <silent> * <Plug>Evanesco_*:ShowSearchIndex<CR>
nmap <silent> # <Plug>Evanesco_#:ShowSearchIndex<CR>
```

I tested these on my configuration so I think they should work but let me know if this doesn't fix the problem for you.  You could also make these a bit more robust with a function call/`feedkeys()` instead of a direct mapping, but I figured it would be easier to keep it simple.

**Comment by dbmrq** [comment]
It works, thanks! :tada:

**Comment by joelostblom** [comment]
Thanks for writing out these bindings, they saved me time! This approach also works with [vim-searchindex](https://github.com/google/vim-searchindex) by removing the first line and replacing `:ShowSearchIndex` with `:SearchIndex`.
